# Generated by Django 4.2.7 on 2023-11-17 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('numsOfSubscribers', models.BigIntegerField()),
                ('startDuration', models.DateField(blank=True, null=True)),
                ('endDuration', models.DateField(blank=True, null=True)),
                ('isFree', models.BooleanField(default=False)),
                ('price', models.FloatField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('discription', models.TextField(blank=True, null=True)),
                ('subscribeType', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscribeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=255)),
                ('companyAddres', models.TextField()),
                ('companyID', models.FileField(upload_to='companyID/')),
                ('companyURL', models.URLField(blank=True, null=True)),
                ('companyEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('responsibleName', models.CharField(max_length=255)),
                ('responsiblePhone', models.CharField(max_length=15)),
                ('responsibleEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('requestStatus', models.CharField(choices=[('underProcess', 'تحت الاجراء'), ('accepted', 'مقبول'), ('rejected', 'مرفوض'), ('canceled', 'ملغي'), ('other', 'اخرى')], max_length=30)),
                ('statusDiscription', models.TextField(blank=True, null=True)),
                ('subscribe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscribes.subscribe')),
            ],
        ),
        migrations.CreateModel(
            name='SubscribeContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusDiscription', models.TextField(blank=True, null=True)),
                ('subscribeContractStatus', models.CharField(choices=[('underProcess', 'جاري التعاقد'), ('paied', 'مدفوع'), ('unpaied', 'غير مدفوع'), ('canceled', 'ملغي'), ('rejected', 'مرفوض'), ('other', 'اخرى')], max_length=30)),
                ('numsOfOrganization', models.IntegerField()),
                ('numsOfUsers', models.IntegerField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('paiedAmount', models.FloatField()),
                ('recieptFile', models.FileField(upload_to='recieptFile/')),
                ('contractFile', models.FileField(upload_to='contractDiscription/')),
                ('contractDiscription', models.TextField(blank=True, null=True)),
                ('contractAproval', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=False)),
                ('subscribeOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscribes.subscribeorder')),
            ],
        ),
    ]
