# Generated by Django 4.2.7 on 2023-11-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribeorder',
            name='requestStatus',
            field=models.CharField(choices=[('underProcess', 'تحت الاجراء'), ('accepted', 'مقبول'), ('rejected', 'مرفوض'), ('canceled', 'ملغي'), ('other', 'اخرى')], default='تحت الاجراء', max_length=30),
        ),
    ]
