# Generated by Django 4.2.7 on 2023-11-19 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscribes', '0002_alter_subscribeorder_requeststatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribeorder',
            name='companyuser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
