# Generated by Django 4.2.7 on 2023-11-19 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscribes', '0003_subscribeorder_companyuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribeorder',
            name='companyuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
