# Generated by Django 4.2.7 on 2023-11-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribes', '0004_alter_subscribeorder_companyuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribeorder',
            name='companyNo',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
