# Generated by Django 4.2.7 on 2023-11-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribes', '0005_subscribeorder_companyno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribeorder',
            name='companyNo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
